# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bird Nerds
email: vin.piotrowski@gmail.com
description: Join Vince and Sandra as they trek through vast tracks of wilderness in Alberta, Canada searching for birds.  Become an aficonado with tips, tricks and tools for acheieving expert levels of Bird Nerdery.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://birdnerds.ca/"

# Build settings
markdown: kramdown
