# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bird Nerds
email: vin.piotrowski@gmail.com
description: Join Vince Piotrowski and Sandra Mills as they trek around Calgary, Alberta and abroad searching for birds.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://birdnerds.ca/"
birdCount: 363
abBirdCount: 211
expeditionCount: 52

# Build settings
markdown: kramdown
