# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bird Nerds
email: vinpiot@gmail.com
description: Join Vince and Sandra as they trek around Calgary, Alberta and abroad searching for birds.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://birdnerds.ca/"
birdCount: 412
abBirdCount: 229
expeditionCount: 73

# Build settings
markdown: kramdown

exclude: ['_site', '.idea']
