# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bird Nerds
email: vin.piotrowski@gmail.com
description: Vincent and Sandra go searching for birds in Alberta and talk bird nerd craft.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://birdnerds.ca/"

# Build settings
markdown: kramdown
